# Generated by Django 4.2.6 on 2023-11-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
